---
title: "D. Beta Diversity"
Author: Monica Mweetwa
Date: 20th May 2024
---

1. Set working directory
```{r setup}
    #knitr::opts_knit$set(root.dir = normalizePath("C:/Users/Monica/Dropbox/AMAZE")) 
    knitr::opts_knit$set(root.dir = normalizePath("~/Library/CloudStorage/Dropbox/AMAZE")) 
```

2. load libraries
```{r}
library(pacman)
pacman::p_load(phyloseq, 
               ggplot2, 
               tidyverse,
               microViz,
               MicrobiomeStat)
source("Code/3. SupplementationAnalysis/OrdPlot_Functions.R")
```

3. Load data
```{r}
load("Inputs/RData/AMAZE_ps_filtered_pairs.RData")
amaze_dup
```

Intervention Arms
```{r}
palette <- c("#E31A1C", "#1F78B4", "#FB9A99", "#33A02C","#FDBF6F", "#B2DF8A","#A6CEE3", "#BA7A70", "#9D4E3F", "#829BAB")

#1. Duodenum
amaze_dup.duod <- subset_samples(amaze_dup, Sample.Type == "Duodenal Aspirate")
duod.plot <- amaze_dup.duod %>%
  tax_transform("identity", rank = "Genus") %>%
  # when no distance matrix or constraints are supplied, PCA is the default/auto ordination method
  dist_calc("bray") %>% # if using this, the transform line should b:  tax_transform("identity", rank = "Genus")
  ord_calc(method = "PCoA") %>%
  ord_plot(color = "InterventionArm", shape = "Timepoint", plot_taxa = NULL, size = 5, auto_caption = NA, scaling = "none", expand = TRUE,
           tax_lab_style = tax_lab_style(type = "text", size = 4, check_overlap = TRUE)) +
  scale_color_manual(values = palette) +
  theme(panel.grid.major = ggplot2::element_blank(),
        panel.grid.minor = ggplot2::element_blank(),
        #panel.background = ggplot2::element_blank(),
        axis.text = ggplot2::element_text(color = "black",
                                          size = 16),
        legend.position = "right",
        legend.title = ggplot2::element_text(size = 16)) +
  ylab("PC2 (13.7%)") + xlab("PC1 (21.6%)") +
  facet_wrap(~Sample.Type, nrow = 1) + 
  labs(color = "Intervention Arms") +
  scale_fill_manual(values = palette) +
  theme_classic()

#2. Stool
amaze_dup.stool <- subset_samples(amaze_dup, Sample.Type == "Stool")
#plot
stool.plot <- amaze_dup.stool %>%
  tax_transform("identity", rank = "Genus") %>%
  # when no distance matrix or constraints are supplied, PCA is the default/auto ordination method
  dist_calc("bray") %>% # if using this, the transform line should b:  tax_transform("identity", rank = "Genus")
  ord_calc(method = "PCoA") %>%
  ord_plot(color = "InterventionArm", shape = "Timepoint", axes = 1:3, plot_taxa = NULL, size = 5, auto_caption = NA, scaling = "none", expand = TRUE,
           tax_lab_style = tax_lab_style(type = "text", size = 4, check_overlap = TRUE)) +
  scale_color_manual(values = palette) +
  theme(panel.grid.major = ggplot2::element_blank(),
        panel.grid.minor = ggplot2::element_blank(),
       # panel.background = ggplot2::element_blank(),
        axis.text = ggplot2::element_text(color = "black",
                                          size = 16),
        legend.position = "right",
        legend.title = ggplot2::element_text(size = 16)) +
  ylab("PC2 (8.5%)") + xlab("PC1 (15.2%)")+
  facet_wrap(~Sample.Type, nrow = 1) + 
  labs(color = "Intervention Arms") +
  scale_fill_manual(values = palette) +
  theme_classic()

ggsave("Outputs/3. SupplementationAnalysis/BetaDiversity/BetaPlot_duod.png", plot = duod.plot, dpi = 600, device = "png", width = 18, height = 16, units = "cm")
ggsave("Outputs/3. SupplementationAnalysis/BetaDiversity/BetaPlot_Stool.png", plot = stool.plot, dpi = 600, device = "png", width = 18, height = 16, units = "cm")

#Export combined plot
library(ggpubr)
beta.int.plot <- ggarrange(duod.plot, stool.plot, ncol = 2, nrow = 1, common.legend = T, legend = "right") +
  theme(legend.position = "right",
        legend.direction = "vertical")
ggsave("Outputs/3. SupplementationAnalysis/BetaDiversity/BetaDiv_combined.png", plot = beta.int.plot, dpi = 600, device = "png", width = 24, height = 36, units = "cm")

#save for combined plots
save(duod.plot, stool.plot, file = "Inputs/RData/ForCombinedPlots/BetaPlot1.RData")
save(beta.int.plot, file = "Inputs/RData/ForCombinedPlots/BetaPlot2.RData")
```
