---
title: "Table One"
Author: Monica Mweetwa
---
Set working directory
```{r setup}
    knitr::opts_knit$set(root.dir = normalizePath("/Users/monica_mweetwa/Library/CloudStorage/Dropbox/AMAZE"))
 #knitr::opts_knit$set(root.dir = normalizePath("C:/Users/Monica/Dropbox/AMAZE")) 
```

Load packages
```{r include=FALSE}
library(ggpubr)
library("ggplot2")
library(tableone)
library(tidyverse)
library(readr)
library(ggVennDiagram)
library(tidyverse)
library(boot)
library(table1)
```

Load Data
```{r}
sample_metadata <- read_csv("Inputs/Table1.csv")
for_venn <- read_csv("Inputs/TabelForVenn.csv")
```

Create a Venn diagram that shows the number of samples common and unique to each sample type
```{r}
g1 <- ggVennDiagram(for_venn,
                    label = "count",  #Use counts instead of percent
                    label_alpha = 0,  #Remove label background 
                    label_size = 8,   #Set label size
                    set_size = 6,     #Set label size
                    stroke_size = 0.5, 
                    set_name_size = 12,
                    show_intersect = FALSE,
                    category.names = c("Duodenal\nAspirate\n(n=69)",
                                       "Stool\n(n=79)")) +
  ggplot2::scale_fill_gradient(low="purple",high = "yellow",limits=c(0,80), name = "Number of\nSamples") +
  scale_x_continuous(expand = expansion(mult = .25)) +
  #scale_y_continuous(expand = expansion(mult = .2)) +
  theme(legend.position = "right",
        legend.text = element_text(size = 16), 
        legend.title = element_text(size=18, face="bold"),
        #legend.key.height = unit(1, "cm"),
        legend.key = element_blank(),
        legend.background = element_blank(),
        legend.box.background = element_blank())
        #panel.background = element_rect(fill = "white"),
        #plot.background = element_rect(fill = "white", color = "white"))

#Save plot
ggsave("Outputs/1. TableOne/SuppFig1_SampleCounts.tiff", plot = g1, dpi = 600, device = "tiff", width = 30, height = 24, units = "cm")
```

Get summary stats
```{r}
#Recode some variables
sample_metadata$sexchar <- ifelse(sample_metadata$sex == 1, "Male", "Female")
sample_metadata$timepoint2 <- ifelse(sample_metadata$Timepoint == "Pre-Intervention", "A", "B")
sample_metadata$timepoint2 <- factor(sample_metadata$timepoint2,
                                     levels=c('A','B'),
                                     labels=c("Pre-Intervention", # Reference
                                              "Post-Intervention"))
label(sample_metadata$Age) <- "Age (years)"
label(sample_metadata$sexchar) <- "Sex"
label(sample_metadata$bmi_nustart) <- "BMI (kg/m2)"
label(sample_metadata$HIV_Status) <- "HIV Status"
label(sample_metadata$muac) <- "Muac (cm)"
label(sample_metadata$VH_mean) <- "Villus Height (μm)"
label(sample_metadata$VW_mean) <- "Villus Width (μm)"
label(sample_metadata$CD_mean) <- "Crypt Depth (μm)"
label(sample_metadata$CLE_Fields) <- "Fluorescein leak, % fields"
label(sample_metadata$LPS) <- "LPS, EU/mL"
label(sample_metadata$CRP) <- "CRP, μmol/mL"
label(sample_metadata$SCD14) <- "sCD14, μmol/mL"
label(sample_metadata$GLP2) <- "GLP2, ng/mL"

#table 1B - stratified by intervention & timepoint
tabel1B <- table1(~ Age + sexchar + HIV_Status + bmi_nustart + muac + LPS + CRP + SCD14 + GLP2 + CD_mean + VH_mean + VW_mean + CLE_Fields | Intervention_arm+timepoint2, data = sample_metadata,
       render.continuous=c(.="Median [Min, Max]"))

#save table
library(flextable)
library(htmlTable)
library(htmltools)
# Convert the table to an HTML object
html_tbl <- htmlTable(tabel1B)
# Save the HTML object to a file
save_html(html_tbl, "Outputs/1. TableOne/table1.html")
```
